# Generated by Django 5.0.1 on 2024-01-03 05:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='CIK',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='asset_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='fiscal_year_end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='latest_quarter',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('o', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('l', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('v', models.BigIntegerField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
