# Generated by Django 5.0.1 on 2024-01-03 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_cik_stock_address_stock_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='data',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='stock',
            name='data',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='stock',
            name='latest_quarter',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
