# Generated by Django 5.0.1 on 2024-01-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_price_data_alter_stock_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
