# Generated by Django 5.0.1 on 2024-01-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_remove_portfolio_positions_portfolio_cash_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1),
        ),
    ]
